# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dacfa18f4805ec9a5b8e7e515b9dcb3ad7ffdab7e88eb665fa77649e8678c685d7ab042084f03348c4c1d21ebb680227fa4442d849a462cc5e424763dc28059

test:
  secret_key_base: bc830bdf56bac96ca7f3b0e76acd53e07a17f2fbc854a251b71eed0d991b6109f798c6a60069fcd52fea0dfc81471ede08362ddafbf31f36d6dbf71ed1c1bad8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
